language: python
cache:
  timeout: 3600
  pip: true
  directories:
    - $HOME/.docker
services:
  - docker
env:
  global:
    - ANSIBLE_FORCE_COLOR=1
    - docker_image=quay.io/loganv/docker-ci
    - docker_command=/lib/systemd/systemd
    - cache_dir=$HOME/.docker
  matrix:
  # LINTERS
  - TOXENV=linters
    CACHE_NAME=linters
  # ANSIBLE 2.1 (NEWTON)
  - >
    TOXENV=functional_2.1
    docker_image_tag=ubuntu-trusty
    docker_command=/sbin/init
    CACHE_NAME=trusty
  - >
    TOXENV=functional_2.1
    docker_image_tag=ubuntu-xenial
    CACHE_NAME=xenial
  # ANSIBLE 2.2 (OCATA)
  - >
    TOXENV=functional_2.2
    docker_image_tag=ubuntu-xenial
    CACHE_NAME=xenial
  - >
    TOXENV=functional_2.2
    docker_image_tag=centos-7
    CACHE_NAME=cent7
  # ANSIBLE stable (OSA MASTER)
  - >
    TOXENV=functional_stable
    docker_image_tag=ubuntu-xenial
    CACHE_NAME=xenial
  - >
    TOXENV=functional_stable
    docker_image_tag=centos-7
    CACHE_NAME=cent7
  - >
    TOXENV=functional_stable
    docker_image_tag=opensuse-42.2
    CACHE_NAME=suse42
    docker_command=/usr/lib/systemd/systemd
before_install:
  # Load cached docker images
  - if [[ -d ${cache_dir} ]]; then ls ${cache_dir}/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - if [[ -n ${docker_image_tag} ]]; then docker pull ${docker_image}:${docker_image_tag}; fi
install:
  - pip install tox
script:
  - tox
before_cache:
  # Save tagged docker images
  - >
    mkdir -p ${cache_dir} && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e ${cache_dir}/$1.tar.gz || docker save $0 | gzip -2 > ${cache_dir}/$1.tar.gz'
notifications:
  email: false
  slack:
    rooms:
      secure: c2G5zn3ClbetNigC0cpcy4XFQhf7Toit/lN8JpwAdPZU1IT7WzyIY7q8U1f4RsjMhEdeaKLgdDY+hx/G16lZ5VnzrfPoyjMBrbHgXXZLGSl80BW7+u+DMgz9ggxCddtBZw1ETMJgBF44dSDOJuLT0pDEi7uksJEyq9pbQgIOZtrJYI5WBOOkEClNoECSfklXGVxwsJ9jr9y7mZAwq5DuaHjbD15yB7/ClMRubbMOnG5TxrlibmO2udbb/iNeDj/g7JVQ3uNBXkduRbWpr9bEWqLLp+J4Iwc8yItJmuxgzq0PE6pRN2E+MiyZKMreJPIl0qXanTe+pzOLSe9JI0lT3D8qs3ZwlCuUiURQrV2cvH/s0/MUoVQckZ6i1zp+6JPJtFWC8UYm+QPdbwXrc72aM29Do6SbFoPrCBPSoFVzCLRoMPEv50LVjFMkwWen6aCeJr+40dDpgr0sd6TB/hwPvguRQ676XlStnY2JwAU3egYVOkgwvz+VQ6SS66tY309Vy2T+g+mXtCxldvyC7lxavdEmb8NiiisDb9a6aOtZB//s84IHfpd69bSjpSPV/N4Lp9litWiNEUQpXdd79tPDf7WJqhd0VlnGFbqQhsaaANxIRdL9BrFDFHCh679T0wQt+Ntf5XVqkJv81UP2fYNBBMwF+o5ZYeFGLh/iAsrjzO8=
