---
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Update resolvers
  template:
    src: resolvconf-base.j2
    dest: "/etc/resolv.conf"
  tags: resolvconf-config

- name: Check if resolvconf directory exists
  stat:
    path: "/etc/resolvconf/resolv.conf.d"
  register: resolvconf_dir
  tags: resolvconf-config

- name: Update resolvconf base
  template:
    src: resolvconf-base.j2
    dest: "/etc/resolvconf/resolv.conf.d/base"
  when: resolvconf_dir.exists
  tags: resolvconf-config

- name: Update resolvconf tail
  copy:
    content: "# Null tail\n"
    dest: "/etc/resolvconf/resolv.conf.d/tail"
  when: resolvconf_dir.exists
  tags: resolvconf-config
