---

- name: Update resolvers
  template:
    src: resolvconf-base.j2
    dest: "/run/resolvconf/resolv.conf"
  tags: resolvconf-config

- name: Update resolvconf base
  template:
    src: resolvconf-base.j2
    dest: "/etc/resolvconf/resolv.conf.d/base"
  tags: resolvconf-config

- name: Update resolvconf tail
  copy:
    content: "# Null tail\n"
    dest: "/etc/resolvconf/resolv.conf.d/tail"
  tags: resolvconf-config
